# -*- coding: utf-8 -*-
"""p1-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-7eLdY42akK1m6UEntquqeoOBqUDSi7
"""

print("hi")
print("g")