# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q-7eLdY42akK1m6UEntquqeoOBqUDSi7
"""

print("hi")

my_list = [1,2,3]
print(my_list)